import sys,json,collections,re,xml.etree.ElementTree as ET
from pathlib import Path
sys.path[:0]=['/private/tmp/unfold-s8-final-boundary-review/scripts','/private/tmp/unfold-s8-final-boundary-review']
from report_s8_demonstration import blocks
from model_unfolder.preview import svg_views
p=Path(sys.argv[1]);ir=json.loads((p/'ir.json').read_text());inventory=json.loads((p/'inventory.json').read_text()) if (p/'inventory.json').exists() else None;rows=list(blocks(ir));ids=set()
for _,svg in svg_views((p/'page.html').read_text()):
 for node in ET.fromstring(svg).iter():
  if 'uf-node' in node.get('class','').split() and node.get('data-id'):ids.add(node.get('data-id'))
explicit={x['source_instance_path'] for x in rows if 'source_instance_path' in x};drawn={x['source_instance_path'] for x in rows if 'source_instance_path' in x and x.get('id') in ids};u=ir.get('extras',{}).get('unet',{});out={'scope':'Saved-artifact exact placement audit, not regenerated S7 reconciliation or execution evidence. Installed-version constructor reconstruction from published config; no checkpoint weights/historical library execution.','canonical_path_citations':sorted(explicit),'actual_svg_path_citations':sorted(drawn),'grouped_paths':[],'grouping_note':'No RenderEvent grouping archive supplied; no grouped occurrence inferred from ancestor placement.','stage_block_ids':u.get('stage_block_ids'),'context_routes':u.get('context_routes'),'skip_routes':u.get('skip_routes'),'unbound_bookend_ids':u.get('other_block_ids'),'primary_region_count':len(u.get('primary_regions',[])),'parameter_total':u.get('parameter_shapes',{}).get('total'),'fact_keys':sorted(json.loads((p/'facts.json').read_text())),'ship_findings':ir.get('extras',{}).get('ship_findings')}
if inventory:
 mods={x['path']:x for x in inventory['modules']};paths=set(mods);missing=paths-explicit;out.update(constructed_count=len(paths),constructed_paths=sorted(paths),canonical_placed_count=len(paths & explicit),actual_svg_placed_count=len(paths & drawn),uncited_paths=sorted(missing),actual_svg_uncited_paths=sorted(paths-drawn),orphan_citations=sorted(explicit-paths),uncited_classes={x:mods[x]['class_ref'] for x in sorted(missing)},conv_in_parameters=mods.get('conv_in',{}).get('parameters'),stage_paths={kind:sorted(x for x in paths if re.fullmatch(kind+r'\.\d+',x)) for kind in ['down_blocks','up_blocks']},mid_paths=[x for x in paths if x=='mid_block'],runtime_provenance=inventory.get('provenance'))
(p.parent/'placement-shape-audit.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k in ['constructed_count','canonical_placed_count','actual_svg_placed_count','uncited_paths','actual_svg_uncited_paths','orphan_citations','uncited_classes','conv_in_parameters','stage_paths','mid_paths','parameter_total','context_routes','unbound_bookend_ids']},indent=2))
