from pathlib import Path
import json,hashlib,gzip,shutil
base=Path('/Users/soumil/Code/Projects/Understand/llmvisualizer');run=Path('/private/tmp/unfold-s8-context-phase-5227e9c');receipt=base/'unfold-pkg/verification/receipts/S8-final-render-5227e9c';page=base/'z-docs/12-design/S8/final-5227e9c';receipt.mkdir();page.mkdir();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
checks=list(run.glob('*/result.json'));assert len(checks)==11
raw=json.loads((run/'raw-control-identity.json').read_text());assert len(set(raw.values()))==1
rows=[];deltas=[]
for result in sorted(checks):
 case=result.parent;name=case.name;d=json.loads(result.read_text());assert all(not v for v in d['checks'].values());assert d['render_events_identical'];target=receipt/name;target.mkdir();source=Path(d['source_case']);prior=Path('/private/tmp/unfold-s8-solid-f7baef5')/name/'after';pb=json.loads((prior/'result.json').read_text());assert d['source_before']==d['source_after']
 for f in ('result.json','render-events.json.gz'):shutil.copy2(case/f,target/f)
 for f in ('page.html','ir.json','render-input.json'):(target/(f+'.gz')).write_bytes(gzip.compress((case/f).read_bytes(),mtime=0))
 shutil.copy2(case/'page.html',page/(name+'.html'))
 event_sha=hashlib.sha256(gzip.decompress((case/'render-events.json.gz').read_bytes())).hexdigest();assert event_sha==pb['render_event_sha256']
 source_delta={k:{'prior_sha256':pb['source_before'].get(k),'final_sha256':d['source_before'].get(k)} for k in sorted(set(pb['source_before'])|set(d['source_before'])) if pb['source_before'].get(k)!=d['source_before'].get(k)}
 historical=(f'S8-generalization-c38b008/{name}/ordinary' if name in ('sdxl-refiner','sdxl-inpainting','ddpm-cifar10') else 'S8-final-c38b008/sd-v1-4/ordinary' if name=='sd14-ordinary' else 'S8-final-c38b008/sdxl/'+name.removeprefix('sdxl-'))
 row={'case':name,'historical_parse_receipt':historical,'historical_parse_input_pins':d['saved_input_pins'],'final_projection_renderer_commit':'5227e9cb05d5cfeca414a26615fd158bc6c83650','prior_actual_html_sha256':d['prior_html_sha256'],'final_actual_html_sha256':d['actual_html_sha256'],'final_actual_html':str(page/(name+'.html')),'final_ir_sha256':sha(case/'ir.json'),'final_render_input_sha256':sha(case/'render-input.json'),'added_reference_card_count':len(d['added_context_reference_parent_ids']),'added_actual_card_count':d['added_actual_card_count'],'all_five_existing_validators':d['checks'],'all_svg_bytes_identical_to_f7':True,'render_event_count':d['after_event_count'],'render_event_sha256_before_and_after':event_sha,'render_event_bytes_identical':True,'production_source_delta_from_f7':source_delta,'blessed':False};rows.append(row)
 delta={'case':name,'preserved_old_new_model_differential':(historical.rsplit('/',1)[0]+'/differential-report.json.gz' if name not in ('sdxl-refiner','sdxl-inpainting','ddpm-cifar10') else None),'reference_additions':[{'parent_card_id':p,'added_card_id':'unet_context_0','cause':'Same source-proven root context input must have its existing inspect card at the next panel depth.','source_fact_keys':['root.denoiser.context_connections'],'new_constructed_occurrence':False} for p in d['added_context_reference_parent_ids']],'render_delta':{'actual_card_count_added':d['added_actual_card_count'],'svg_changes':[],'quantities_changed':False,'render_events_changed':False},'prior_stroke_caption_phase':f'S8-solid-stroke-f7baef5/{name}/comparison.json','prior_component_entry_phase':f'S8-component-render-96d0c1e/{name}' if name in ('sdxl-refiner','sdxl-inpainting','ddpm-cifar10') else None,'automatic_approval_or_blessing':False};deltas.append(delta)
summary={'scope':'Saved historical facts plus exact captured full IR; final projector additions and actual renderer only. No model/source reader execution is restamped as final fresh execution.','production_commit':'5227e9cb05d5cfeca414a26615fd158bc6c83650','cases':rows,'raw_ordinary_rewrite_unchanged':raw,'case_count':len(rows),'all_checks_pass':True,'table_verification':'Owned by executor final matrix lane; this phase proves unchanged full render-event bytes and explicitly enumerated presentation IR reference additions only.','blessed':False};(receipt/'summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n');(page/'manifest.json').write_text(json.dumps(summary,indent=2,sort_keys=True)+'\n');(receipt/'incremental-output-ledger.json').write_text(json.dumps(deltas,indent=2,sort_keys=True)+'\n');(page/'incremental-output-ledger.json').write_text(json.dumps(deltas,indent=2,sort_keys=True)+'\n')
for f in ('verify.py','persist.py','run.log','raw-control-identity.json'):shutil.copy2(run/f,receipt/f)
(receipt/'README.md').write_text('''# Final saved-evidence projection and rendering phase:5227e9c

All eleven cases pass at committed5227e9cb05d5cfeca414a26615fd158bc6c83650: seven SDXL conditions including unchanged control, SD-v1-4 ordinary, refiner, inpainting and unconditional DDPM. This is an additional saved-evidence projection/rendering phase. Historical model construction, source reads, scratch imports and condition reports keep their original pins; none is restamped as a new final-source model execution. Executor owns the separate final matrix/source reconciliation lane.

For each case the old f7 and final projector consume the same exact saved fact values and the same empty outer handoffs. Removing only new context-input reference children makes those bounded projector outputs exactly equal. The new reference cards must equal each case's original canonical root context card in every field. Only these exact additions are transported into the saved complete IR; the limited empty-handoff projection never replaces the full pipeline. Fresh-original-JSON equality after removing these additions, exact captured warning metadata, Diagram input and parameter record checks preserve the supplied components, findings, identities and quantities.

The final actual HTML differs from f7 by exactly one additional shared deep context card for each case with established context routing. The missing-evidence case and DDPM have no such additions and their pages remain byte-identical. Every SVG is byte-identical to f7. Full canonical render-event sequences are byte-identical, with list/tuple order preserved. All five existing validators pass: click coupling, block tree, unique reference IDs, no dotted arrows, no dotted boundaries. Source manifests before/after each projection/render are identical. Original facts and qualified-fact hashes remain unchanged.

Final ordinary, supported equivalent rewrite and unchanged scratch-control actual HTML bytes are equal: d499a0e62b809bbf52f6408255628b85a6bb1c1b70c773591bcc00e7ee07b047. summary.json enumerates original/final page hashes, historical parse inputs, final IR/render inputs, full event hashes and source differences. Each final actual page, IR, captured render input and event sequence is persisted.

incremental-output-ledger.json names every added reference parent, its existing context connection fact, and the prior exact stroke/caption correction per case. The extra trio's prior component-label correction is linked separately. Historical old/new differential classifications and owner-review decisions remain unchanged; this ledger does not approve or bless them. DDPM retains its six unbound bookend connections and open stage-target limits. This phase adds no mechanism proof or constructed occurrence.

Actual pages: root z-docs/12-design/S8/final-5227e9c/index.html. Previous actual pages and interrupted9712 receipts remain preserved. No model or pytest lane ran. No additional native redraw was needed: every actual SVG matches the already inspected f7 diagrams exactly.
''')
links=''.join(f'<li><a href="{r["case"]}.html">{r["case"]}: actual page</a> — {r["added_reference_card_count"]} declared context references; {r["added_actual_card_count"]} additional shared inspection card</li>' for r in rows)
(page/'index.html').write_text('<!doctype html><meta charset="utf-8"><title>S8 final actual pages ·5227e9c</title><style>body{font:16px system-ui;max-width:1100px;margin:40px auto;line-height:1.6}li{margin:10px 0}code{overflow-wrap:anywhere}</style><h1>S8 final actual pages ·5227e9c</h1><p>Eleven saved-evidence projection/render replays. Existing click, block-tree, unique-ID and solid-stroke checks pass. All diagrams match the previous inspected diagrams exactly; the context source now has its proper deep inspection card. No models rerun and no outputs blessed.</p><p>Ordinary/rewrite/unchanged raw HTML SHA-256: <code>'+next(iter(raw.values()))+'</code>.</p><p>Historical source/model runs retain their original pins. DDPM still carries six unbound bookends and open stage-target limitations.</p><ul>'+links+'</ul><p><a href="manifest.json">Exact source/input/output/event hashes</a> · <a href="incremental-output-ledger.json">Incremental output ledger</a> · <a href="../final-f7baef5/index.html">Preserved f7 pages</a> · <a href="../final-c38b008/render-phase/index.html">Original controlled experiment pages</a></p>')
manifest={str(p.relative_to(receipt)):sha(p) for p in sorted(receipt.rglob('*')) if p.is_file() and p.name!='artifact-sha256.json'};(receipt/'artifact-sha256.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n');print(json.dumps({'receipt':str(receipt),'decision_page':str(page/'index.html'),'summary_sha256':sha(receipt/'summary.json'),'index_sha256':sha(page/'index.html')}))
