#!/usr/bin/env python3
"""Generate/check the current U3 legacy-reader and parse-authority inventory."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "U3_CURRENT_READER_INVENTORY.md"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from model_unfolder.evidence.legacy_reader_quarantine import (  # noqa: E402
    LEGACY_PARSE_CALLER_FINGERPRINT,
    LEGACY_READER_IMPLEMENTATION_FINGERPRINT,
    LEGACY_SEMANTIC_READERS,
    PARSE_AUTHORITY_SITES,
    legacy_reader_quarantine_problems,
)


def render() -> str:
    problems = legacy_reader_quarantine_problems(ROOT)
    if problems:
        raise RuntimeError("\n".join(problems))
    rows = sorted(
        LEGACY_SEMANTIC_READERS,
        key=lambda row: (int(row.migration_unit[1:]), row.symbol))
    parse_rows = sorted(
        PARSE_AUTHORITY_SITES,
        key=lambda row: (row.category, row.site.path, row.site.enclosing_symbol))

    out = [
        "# U3 Current Reader Inventory — Generated",
        "",
        "> Generated by `scripts/generate_u3_reader_inventory.py` from the",
        "> blocking code register. Do not edit this file manually.",
        "",
        "This is the current authority/deletion worklist. The older",
        "`docs/U3_READER_INVENTORY.md` is retained as historical reconnaissance.",
        "",
        "## Summary",
        "",
        f"- quarantined semantic readers: **{len(rows)}**",
        f"- exact evidence-layer `ast.parse` sites: **{len(parse_rows)}**",
        f"- legacy model-source parse sites: **{sum(r.category == 'legacy_model_source' for r in parse_rows)}**",
        f"- frozen reader/helper implementation digest: `{LEGACY_READER_IMPLEMENTATION_FINGERPRINT}`",
        f"- frozen legacy-parse caller digest: `{LEGACY_PARSE_CALLER_FINGERPRINT}`",
        "",
        "## Authority classes",
        "",
        "- **Migrated exact-owner readers:** live receipts and definitions are",
        "  indexed in `docs/U3_RUNBOOK.md`; they have no raw-files row here.",
        "- **Neutral infrastructure:** `central_program_index` and",
        "  `address_bootstrap` parse-authority rows.",
        "- **Quarantined semantic readers:** the exact table below.",
        "- **Repository/test scanners:** `repository_audit` and `test_guard` rows.",
        "- **Dead symbols/sites:** never retained as rows; a stale row is blocking.",
        "",
        "## Quarantined semantic readers",
        "",
        "| Future unit | Definition | Exact production callers | Reason | Deletion condition |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        callers = "<br>".join(f"`{caller}`" for caller in row.callers) or "none"
        out.append(
            f"| {row.migration_unit} | `{row.definition_path}::{row.symbol}` "
            f"| {callers} | {row.reason} | {row.deletion_condition} |")

    out.extend([
        "",
        "## Parse authority",
        "",
        "| Category | Exact site | Future deletion unit | Reason |",
        "|---|---|---|---|",
    ])
    for row in parse_rows:
        site = f"{row.site.path}::{row.site.enclosing_symbol}"
        out.append(
            f"| `{row.category}` | `{site}` | {row.deletion_unit or '—'} "
            f"| {row.reason or 'lawful retained authority'} |")

    out.extend([
        "",
        "## Blocking rules",
        "",
        "- A new or renamed `*_from_files` definition fails.",
        "- A new production caller of a quarantined reader fails.",
        "- A reader body or same-module helper-closure change fails.",
        "- A new caller of a legacy model-source parse authority fails.",
        "- Moving a reader or parse site fails.",
        "- A new evidence-layer `ast.parse` site fails.",
        "- A future unit deletes its reader/parse rows in the same commit as the old authority.",
        "- Absence from this inventory does not make a parser lawful; the static census must classify it.",
        "",
    ])
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.write:
        OUTPUT.write_text(text, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if current != text:
        print(f"{OUTPUT.relative_to(ROOT)} is stale", file=sys.stderr)
        return 1
    print("U3 reader inventory is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
