from pathlib import Path
import collections,gzip,hashlib,json
R=Path('/Users/soumil/Code/Projects/Understand/llmvisualizer/unfold-pkg');B=R/'verification/receipts/S9-A-schema-candidate-fff99e22/new-resume/reviews';O=B/'nested147-current32-audit';O.mkdir(exist_ok=True);assert not list(O.iterdir());prior=B/'current31-recovered-cause-audit';P=Path('/private/tmp/unfold-s9a-thirtysecond/current-pages');C=P/'capture';F=R/'.claude/worktrees/verify-s9-a-thirtysecond'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def load(p):return json.loads(gzip.decompress(p.read_bytes()) if p.suffix=='.gz' else p.read_bytes())
def save(p,v):p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
result=load(P/'result.json');assert result['passed'] and result['pins_equal'] and result['before']==result['after'] and result['artifacts_before']==result['artifacts_after'];assert load(P/'pins-before.json')==load(P/'pins-after.json')
fleet=load(C/'result.json');assert fleet['captured_count']==39 and fleet['failed_count']==0;fleet_rows={v['slug']:v for v in fleet['models']}
rows=[]
for p in sorted(prior.glob('*/canonical-delta-causes.json')):
 for v in load(p):
  if 'limit' in v['detail']:rows.append({'slug':p.parent.name,**v})
assert len(rows)==147;models={};allrows=[];fields=collections.Counter();causes=collections.Counter();targets=set();obligations=set()
for slug in sorted({r['slug'] for r in rows}):
 root=C/slug;verified={}
 for name,h in fleet_rows[slug]['artifact_sha256'].items():assert sha((root/name).read_bytes())==h;verified[name]=h
 actual_input=load(root/'input.json');old_input=load(Path('/private/tmp/unfold-s9a-thirtyfirst/preservation-current31/capture/controller/cases')/slug/'attempt-01/input.json')['config'];assert actual_input==old_input
 context=load(root/'render-context-local.json.gz')['context'];facts=load(root/'facts.json');declarations=load(root/'declarations.json');ir=load(root/'ir-before-render.json.gz');assert context['fact_rows']==facts
 model_rows=[]
 for row in [v for v in rows if v['slug']==slug]:
  target=row['detail']['after_obligation']['target'];key=target['owner']+'.'+target['key'];local_key=key.split('.',2)[-1];index=int(row['raw_path'].split('/')[3]);actual=ir['extras']['config_access']['projection_obligations'][index];assert actual==row['detail']['after_obligation']
  leaf=row['raw_path'].split('/')[-1];assert leaf in ('expected_value_status_hash','mechanism','key','owner');fields[leaf]+=1;causes[row['cause']]+=1;targets.add((slug,key));obligations.add((slug,index))
  channels={'render_context_fact_rows':context['fact_rows'],'saved_parent_facts':facts,'saved_parent_declarations':declarations};found={name:{'qualified_key':key in values,'local_key':local_key in values} for name,values in channels.items()};assert not any(any(v.values()) for v in found.values())
  chip_refs=[ref for event in context['chip_events'] for saved_ref in event['chip']['references'] for ref in [json.loads(saved_ref['_record'])] if ref['fact_key'] in (key,local_key)];receipts=[receipt for event in context['events'] for receipt in event['receipts'] if receipt['fact_id']==key];assert not chip_refs and not receipts
  detail={'raw_canonical_delta_path':row['raw_path'],'cause':row['cause'],'field_changed':leaf,'before_obligation':row['detail']['before_obligation'],'after_obligation':actual,'qualified_child_fact_key':key,'local_child_fact_key':local_key,'actual32_obligation_equal_current31':True,'exact_native_record_presence':found,'matching_child_chip_reference_count':len(chip_refs),'matching_child_projection_receipt_count':len(receipts),'closure':'REMAINS_UNVERIFIED_CHILD_NATIVE_HASH','reason':'Actual parent ledger/context snapshot contains no child native value+status+proof record; matching obligation repeats its own asserted expected hash and cannot independently validate it.'};model_rows.append(detail);allrows.append({'slug':slug,**detail})
 models[slug]={'delta_rows':len(model_rows),'unique_obligations':len({int(v['raw_canonical_delta_path'].split('/')[3]) for v in model_rows}),'child_fact_targets':sorted({v['qualified_child_fact_key'] for v in model_rows}),'actual32_input_identical_to_current31':True,'parent_render_fact_rows_equal_saved_native_parent_facts':True,'parent_fact_count':len(facts),'parent_declaration_count':len(declarations),'chip_count':len(context['chip_events']),'artifact_hashes_verified':verified,'rows':model_rows}
refs={}
for name,needle in [('model_unfolder/evidence/context.py','return ParseContext('),('model_unfolder/adapters/transformer/parser.py','_facts = getattr(context, "facts", None)'),('model_unfolder/adapters/diffusor/parser.py','context=_slot_context('),('model_unfolder/encoder_panel.py','return _project_encoder_spec(c, ir, context)'),('model_unfolder/submodel.py','def submodel_spec('),('model_unfolder/diagram.py','fact_rows=dict('),('model_unfolder/renderers/html/render_context.py','fact_rows: dict')]:
 p=F/name;raw=p.read_bytes();lines=raw.decode().splitlines();hits=[i+1 for i,l in enumerate(lines) if needle in l];assert hits;refs[name]={'sha256':sha(raw),'matching_lines':hits,'needle':needle}
summary={'verdict':'LIMIT_REMAINS_ALL147_ROWS_NO_CHILD_NATIVE_RECORD_CAPTURED','delta_rows':147,'unique_consumption_obligations':len(obligations),'unique_child_fact_targets':len(targets),'models_affected':len(models),'changed_field_counts':dict(fields),'source_cause_counts':dict(causes),'claim_proof_fields_changed':0,'claim_kind_fields_changed':0,'actual32_input_and_obligation_matches':147,'native_hash_limits_closed':0,'native_hash_limits_remaining':147,'source_cause':'slot_parse_context creates a separate child ParseContext and FactLedger. Transformer parser writes its native records there. encoder_panel returns a projected sub_model spec; it does not return/register the child native ledger on the parent. Diagram seeds RenderContext.fact_rows from the enclosing IR fact_provenance. Capturing all fields of that RenderContext therefore still captures the parent ledger, not the discarded child ledger.', 'authority':'These rows change consumption-to-fact association metadata, not serialized claim_kind/claim_proof fields. No claim that child proofs were revalidated follows from this absence. Existing source-bound proof validation may occur during actual child parsing, but this saved packet cannot independently recheck child native value/status hashes.', 'source_references':refs,'actual32_lane':result,'actual32_capture_summary_sha256':sha((C/'result.json').read_bytes()),'per_model_counts':{k:v['delta_rows'] for k,v in models.items()},'next_boundary_if_requested':'A separate source-reviewed observer could retain each actual child context native ledger and original proof validation while that context is alive, before encoder_panel projects/returns the sub_model. No such harness, runtime or production change is prepared or performed by this audit.', 'no_runtime_models_or_tests':True,'no_production_or_active_artifact_changes':True,'output_approval':False}
save(O/'summary.json',summary);save(O/'per-model.json',models);save(O/'all147-rows.json',allrows);(O/'audit-source.py').write_bytes(Path('/private/tmp/audit-nested147-current32.py').read_bytes());save(O/'manifest.json',{'files':[{'path':p.name,'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in sorted(O.iterdir()) if p.is_file()]});print(json.dumps({'manifest_sha256':sha((O/'manifest.json').read_bytes()),'summary_sha256':sha((O/'summary.json').read_bytes()),'obligations':len(obligations),'targets':len(targets),'fields':dict(fields),'closed':0},indent=2))
